// <auto-generated />
using System;
using BeachBar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeachBar.Infrastructure.Migrations
{
    [DbContext(typeof(BeachBarDbContext))]
    [Migration("20260526150510_AddDataRiferimento")]
    partial class AddDataRiferimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeachBar.Core.Entities.Consumazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdottoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantita")
                        .HasColumnType("integer");

                    b.Property<int>("SessioneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("SessioneId");

                    b.ToTable("Consumazioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.ImpostazioniSpiaggia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NumeroColonne")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroOmbrelloni")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UltimoResetStatistiche")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ImpostazioniSpiaggia");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NumeroColonne = 4,
                            NumeroOmbrelloni = 20
                        });
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Ombrellone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<bool>("Occupato")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Ombrelloni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = 1,
                            Occupato = false
                        },
                        new
                        {
                            Id = 2,
                            Numero = 2,
                            Occupato = false
                        },
                        new
                        {
                            Id = 3,
                            Numero = 3,
                            Occupato = false
                        },
                        new
                        {
                            Id = 4,
                            Numero = 4,
                            Occupato = false
                        },
                        new
                        {
                            Id = 5,
                            Numero = 5,
                            Occupato = false
                        },
                        new
                        {
                            Id = 6,
                            Numero = 6,
                            Occupato = false
                        },
                        new
                        {
                            Id = 7,
                            Numero = 7,
                            Occupato = false
                        },
                        new
                        {
                            Id = 8,
                            Numero = 8,
                            Occupato = false
                        },
                        new
                        {
                            Id = 9,
                            Numero = 9,
                            Occupato = false
                        },
                        new
                        {
                            Id = 10,
                            Numero = 10,
                            Occupato = false
                        },
                        new
                        {
                            Id = 11,
                            Numero = 11,
                            Occupato = false
                        },
                        new
                        {
                            Id = 12,
                            Numero = 12,
                            Occupato = false
                        },
                        new
                        {
                            Id = 13,
                            Numero = 13,
                            Occupato = false
                        },
                        new
                        {
                            Id = 14,
                            Numero = 14,
                            Occupato = false
                        },
                        new
                        {
                            Id = 15,
                            Numero = 15,
                            Occupato = false
                        },
                        new
                        {
                            Id = 16,
                            Numero = 16,
                            Occupato = false
                        },
                        new
                        {
                            Id = 17,
                            Numero = 17,
                            Occupato = false
                        },
                        new
                        {
                            Id = 18,
                            Numero = 18,
                            Occupato = false
                        },
                        new
                        {
                            Id = 19,
                            Numero = 19,
                            Occupato = false
                        },
                        new
                        {
                            Id = 20,
                            Numero = 20,
                            Occupato = false
                        });
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Disponibile")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Tempesta",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 2,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Scirocco",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 3,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Maestrale",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 4,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Ponente",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 5,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Hot Dog",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 6,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Maxi Toast",
                            Prezzo = 6.00m
                        },
                        new
                        {
                            Id = 7,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Maxi Toast Grecale",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 8,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Hamburger",
                            Prezzo = 9.00m
                        },
                        new
                        {
                            Id = 9,
                            Categoria = "Panini",
                            Disponibile = true,
                            Nome = "Cheeseburger",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 10,
                            Categoria = "Insalate",
                            Disponibile = true,
                            Nome = "Insalata",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 11,
                            Categoria = "Insalate",
                            Disponibile = true,
                            Nome = "Condiglione",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 12,
                            Categoria = "Insalate",
                            Disponibile = true,
                            Nome = "Nizzarda",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 13,
                            Categoria = "Insalate",
                            Disponibile = true,
                            Nome = "Ultima Spiaggia",
                            Prezzo = 14.00m
                        },
                        new
                        {
                            Id = 14,
                            Categoria = "Pizza",
                            Disponibile = true,
                            Nome = "Pizzella Margherita",
                            Prezzo = 6.00m
                        },
                        new
                        {
                            Id = 15,
                            Categoria = "Pizza",
                            Disponibile = true,
                            Nome = "Pizzella Farcita",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 16,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Caprese",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 17,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Crudo e Melone",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 18,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Bresaola Rucola Grana Pomodoro",
                            Prezzo = 15.00m
                        },
                        new
                        {
                            Id = 19,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Crudo Bufala Rucola",
                            Prezzo = 15.00m
                        },
                        new
                        {
                            Id = 20,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Patatine Fritte",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 21,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Pan Fritto",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 22,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Nuggets e Patatine",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 23,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Pan Fritto con Crudo",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 24,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Wurstel e Patatine",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 25,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Cotoletta e Patatine",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 26,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Torta di Verdure",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 27,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Torta di Verdure con Contorno",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 28,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Focaccia al Formaggio",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 29,
                            Categoria = "Piatti",
                            Disponibile = true,
                            Nome = "Focaccia al Formaggio con Pomodoro",
                            Prezzo = 14.00m
                        },
                        new
                        {
                            Id = 30,
                            Categoria = "Pasta",
                            Disponibile = true,
                            Nome = "Penne",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 31,
                            Categoria = "Pasta",
                            Disponibile = true,
                            Nome = "Gnocchi",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 32,
                            Categoria = "Pasta",
                            Disponibile = true,
                            Nome = "Trofie",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 33,
                            Categoria = "Pasta",
                            Disponibile = true,
                            Nome = "Ravioli",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 34,
                            Categoria = "Pasta",
                            Disponibile = true,
                            Nome = "Lasagne",
                            Prezzo = 10.00m
                        },
                        new
                        {
                            Id = 35,
                            Categoria = "Frutta",
                            Disponibile = true,
                            Nome = "Anguria",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 36,
                            Categoria = "Frutta",
                            Disponibile = true,
                            Nome = "Melone",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 37,
                            Categoria = "Frutta",
                            Disponibile = true,
                            Nome = "Macedonia",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 38,
                            Categoria = "Frutta",
                            Disponibile = true,
                            Nome = "Macedonia con Yogurt/Gelato",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 39,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè",
                            Prezzo = 1.30m
                        },
                        new
                        {
                            Id = 40,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè Americano",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 41,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè Decaffeinato",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 42,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Orzo/Ginseng",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 43,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Orzo/Ginseng Grande",
                            Prezzo = 2.00m
                        },
                        new
                        {
                            Id = 44,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè Corretto",
                            Prezzo = 1.80m
                        },
                        new
                        {
                            Id = 45,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè Shakerato",
                            Prezzo = 2.50m
                        },
                        new
                        {
                            Id = 46,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Caffè Shakerato Special",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 47,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Cappuccino",
                            Prezzo = 2.00m
                        },
                        new
                        {
                            Id = 48,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Latte",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 49,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Latte Macchiato",
                            Prezzo = 2.50m
                        },
                        new
                        {
                            Id = 50,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Brioches",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 51,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Focaccia",
                            Prezzo = 2.00m
                        },
                        new
                        {
                            Id = 52,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Pizza",
                            Prezzo = 2.50m
                        },
                        new
                        {
                            Id = 53,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Crema Caffè",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 54,
                            Categoria = "Caffetteria",
                            Disponibile = true,
                            Nome = "Yogurt",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 55,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Acqua 0.5L",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 56,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Acqua 1L",
                            Prezzo = 2.50m
                        },
                        new
                        {
                            Id = 57,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Estathé Brick",
                            Prezzo = 2.00m
                        },
                        new
                        {
                            Id = 58,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Succhi di Frutta",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 59,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Tonica Schweppes",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 60,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Lemonsoda",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 61,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Chinotto di Lurisia",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 62,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Limonata del Tigullio",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 63,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Aloe Vera",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 64,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Lattine",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 65,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Spremuta di Arancia",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 66,
                            Categoria = "Bibite",
                            Disponibile = true,
                            Nome = "Smoothie di Frutta",
                            Prezzo = 6.00m
                        },
                        new
                        {
                            Id = 67,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Birra Raffo Piccola",
                            Prezzo = 3.50m
                        },
                        new
                        {
                            Id = 68,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Birra Raffo Media",
                            Prezzo = 6.00m
                        },
                        new
                        {
                            Id = 69,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Birra Raffo Maxi",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 70,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Birra Raffo Ultra",
                            Prezzo = 12.00m
                        },
                        new
                        {
                            Id = 71,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Heineken",
                            Prezzo = 4.50m
                        },
                        new
                        {
                            Id = 72,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Beck's",
                            Prezzo = 4.50m
                        },
                        new
                        {
                            Id = 73,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Raffo Grezza",
                            Prezzo = 4.50m
                        },
                        new
                        {
                            Id = 74,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Nastro Azzurro Capri",
                            Prezzo = 4.50m
                        },
                        new
                        {
                            Id = 75,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Ceres",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 76,
                            Categoria = "Birre",
                            Disponibile = true,
                            Nome = "Nastro Azzurro 0",
                            Prezzo = 4.50m
                        },
                        new
                        {
                            Id = 77,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Calice Pigato/Vermentino",
                            Prezzo = 5.00m
                        },
                        new
                        {
                            Id = 78,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Calice Prosecco",
                            Prezzo = 6.00m
                        },
                        new
                        {
                            Id = 79,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Pigato Le Creuze",
                            Prezzo = 22.00m
                        },
                        new
                        {
                            Id = 80,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Vermentino Le Creuze",
                            Prezzo = 22.00m
                        },
                        new
                        {
                            Id = 81,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Prosecco Marsuret",
                            Prezzo = 25.00m
                        },
                        new
                        {
                            Id = 82,
                            Categoria = "Vini",
                            Disponibile = true,
                            Nome = "Franciacorta Ca del Bosco",
                            Prezzo = 55.00m
                        },
                        new
                        {
                            Id = 83,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Crodino",
                            Prezzo = 3.50m
                        },
                        new
                        {
                            Id = 84,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Sanbitter",
                            Prezzo = 3.50m
                        },
                        new
                        {
                            Id = 85,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Campari Soda",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 86,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Aperol Spritz",
                            Prezzo = 7.00m
                        },
                        new
                        {
                            Id = 87,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Campari Spritz",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 88,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Hugo",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 89,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Sprutz",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 90,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Negroni",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 91,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Americano",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 92,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Negroni Sbagliato",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 93,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Mojito",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 94,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Gin Tonic",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 95,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Gin Lemon",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 96,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Vodka Tonic",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 97,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Vodka Lemon",
                            Prezzo = 8.00m
                        },
                        new
                        {
                            Id = 98,
                            Categoria = "Aperitivi",
                            Disponibile = true,
                            Nome = "Campari Shakerato",
                            Prezzo = 8.00m
                        });
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Apertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Chiusa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Chiusura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataRiferimento")
                        .HasColumnType("date");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text");

                    b.Property<int>("OmbrelloneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OmbrelloneId");

                    b.ToTable("Sessioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Consumazione", b =>
                {
                    b.HasOne("BeachBar.Core.Entities.Prodotto", "Prodotto")
                        .WithMany("Consumazioni")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachBar.Core.Entities.Sessione", "Sessione")
                        .WithMany("Consumazioni")
                        .HasForeignKey("SessioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Sessione");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.HasOne("BeachBar.Core.Entities.Ombrellone", "Ombrellone")
                        .WithMany("Sessioni")
                        .HasForeignKey("OmbrelloneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ombrellone");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Ombrellone", b =>
                {
                    b.Navigation("Sessioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Prodotto", b =>
                {
                    b.Navigation("Consumazioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.Navigation("Consumazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
