// <auto-generated />
using System;
using BeachBar.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeachBar.Infrastructure.Migrations
{
    [DbContext(typeof(BeachBarDbContext))]
    [Migration("20260513095422_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeachBar.Core.Entities.Consumazione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProdottoId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantita")
                        .HasColumnType("integer");

                    b.Property<int>("SessioneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProdottoId");

                    b.HasIndex("SessioneId");

                    b.ToTable("Consumazioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Ombrellone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<bool>("Occupato")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Ombrelloni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Numero = 1,
                            Occupato = false
                        },
                        new
                        {
                            Id = 2,
                            Numero = 2,
                            Occupato = false
                        },
                        new
                        {
                            Id = 3,
                            Numero = 3,
                            Occupato = false
                        },
                        new
                        {
                            Id = 4,
                            Numero = 4,
                            Occupato = false
                        },
                        new
                        {
                            Id = 5,
                            Numero = 5,
                            Occupato = false
                        },
                        new
                        {
                            Id = 6,
                            Numero = 6,
                            Occupato = false
                        },
                        new
                        {
                            Id = 7,
                            Numero = 7,
                            Occupato = false
                        },
                        new
                        {
                            Id = 8,
                            Numero = 8,
                            Occupato = false
                        },
                        new
                        {
                            Id = 9,
                            Numero = 9,
                            Occupato = false
                        },
                        new
                        {
                            Id = 10,
                            Numero = 10,
                            Occupato = false
                        },
                        new
                        {
                            Id = 11,
                            Numero = 11,
                            Occupato = false
                        },
                        new
                        {
                            Id = 12,
                            Numero = 12,
                            Occupato = false
                        },
                        new
                        {
                            Id = 13,
                            Numero = 13,
                            Occupato = false
                        },
                        new
                        {
                            Id = 14,
                            Numero = 14,
                            Occupato = false
                        },
                        new
                        {
                            Id = 15,
                            Numero = 15,
                            Occupato = false
                        },
                        new
                        {
                            Id = 16,
                            Numero = 16,
                            Occupato = false
                        },
                        new
                        {
                            Id = 17,
                            Numero = 17,
                            Occupato = false
                        },
                        new
                        {
                            Id = 18,
                            Numero = 18,
                            Occupato = false
                        },
                        new
                        {
                            Id = 19,
                            Numero = 19,
                            Occupato = false
                        },
                        new
                        {
                            Id = 20,
                            Numero = 20,
                            Occupato = false
                        });
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Prodotto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Disponibile")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Prezzo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Prodotti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disponibile = true,
                            Nome = "Acqua",
                            Prezzo = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            Disponibile = true,
                            Nome = "Coca Cola",
                            Prezzo = 2.50m
                        },
                        new
                        {
                            Id = 3,
                            Disponibile = true,
                            Nome = "Birra",
                            Prezzo = 3.00m
                        },
                        new
                        {
                            Id = 4,
                            Disponibile = true,
                            Nome = "Spritz",
                            Prezzo = 4.00m
                        },
                        new
                        {
                            Id = 5,
                            Disponibile = true,
                            Nome = "Caffè",
                            Prezzo = 1.20m
                        },
                        new
                        {
                            Id = 6,
                            Disponibile = true,
                            Nome = "Gelato",
                            Prezzo = 2.50m
                        });
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Apertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Chiusa")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("Chiusura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("text");

                    b.Property<int>("OmbrelloneId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OmbrelloneId");

                    b.ToTable("Sessioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Consumazione", b =>
                {
                    b.HasOne("BeachBar.Core.Entities.Prodotto", "Prodotto")
                        .WithMany("Consumazioni")
                        .HasForeignKey("ProdottoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BeachBar.Core.Entities.Sessione", "Sessione")
                        .WithMany("Consumazioni")
                        .HasForeignKey("SessioneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prodotto");

                    b.Navigation("Sessione");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.HasOne("BeachBar.Core.Entities.Ombrellone", "Ombrellone")
                        .WithMany("Sessioni")
                        .HasForeignKey("OmbrelloneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ombrellone");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Ombrellone", b =>
                {
                    b.Navigation("Sessioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Prodotto", b =>
                {
                    b.Navigation("Consumazioni");
                });

            modelBuilder.Entity("BeachBar.Core.Entities.Sessione", b =>
                {
                    b.Navigation("Consumazioni");
                });
#pragma warning restore 612, 618
        }
    }
}
